/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.sgpublic.backsql

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.check
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.boolean
import com.github.ajalt.clikt.parameters.types.int
import com.github.ajalt.clikt.parameters.types.long

object App: CliktCommand(), Config {
    override val dbHost: String by option("--db-host",
            help = "数据库 IP",
            envvar = "BACKSQL_DB_HOST")
            .default("")
            .check("数据库地址不能为空") {
                it.isNotBlank()
            }
    override val dbPort: Int by option("--db-port",
            help = "数据库端口",
            envvar = "BACKSQL_DB_PORT")
            .int()
            .default(3306)
            .check("数据库端口不合法") {
                it in 0 .. 65535
            }

    override val duration: Long? by option("--duration",
            help = "备份任务间隔时间",
            envvar = "BACKSQL_DURATION")
            .long()
    override val cron: String? by option("--cron",
            help = "备份任务 cron 表达式",
            envvar = "BACKSQL_CRON")

    override val keepTime: Long by option("--keep-time",
            help = "备份文件保留时长",
            envvar = "BACKSQL_KEEP_TIME")
            .long()
            .default(-1)
    override val keepCount: Int by option("--keep-count",
            help = "备份文件保留数量",
            envvar = "BACKSQL_KEEP_COUNT")
            .int()
            .default(-1)

    override val now: Boolean by option("--now",
            help = "立即执行一次备份任务")
            .boolean()
            .default(false)
    override val once: Boolean by option("--once",
            help = "只执行一次备份任务")
            .boolean()
            .default(false)

    override fun run() {

    }

    @JvmStatic
    fun main(args: Array<String>) {
        main(args)
    }
}
